name: Draft PDF

on:
  push:
    paths:
      - 'JOSS_submission/paper.md'
      - 'JOSS_submission/paper.bib'

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build draft PDF
      uses: openjournals/openjournals-draft-action@master
      with:
        journal: joss
        paper-path: JOSS_submission/paper.md
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: paper
        path: 'JOSS_submission/paper.pdf'
